### PR TITLE
Support for Contextual Query Language

### PR DESCRIPTION
**Pull request by VishalDalwadi**
_This implementation of CQL was part of the Google Summer of Code 2021 project "Support for Contextual Query Language"._ 

The initial design for CQL implementation was to allow users to create JARs that contain the context set information. These JARs could then be found by a plugin manager and the CQL execution engine could use the context sets to convert the query into relation algebra.

However, after careful consideration, we came upon the current design which is much simpler (both for understanding and implementation). In the current design, the schema takes on the role of Context Set. The schema has tables which in-turn have columns. These two take on the role of index (as specified in the CQL standard spec). Filters are operations taking place on columns and Relations are the output of combine operation ( Joins or Set Operations ) on tables.

### CODE REVIEW

**Comment by vogti** [comment]
Hi @VishalDalwadi Thank you for this contribution. While testing, I found the following bug: It is not possible to sort by a column that is not projected (results in a null pointer). Here is a query to reproduce this:
`relation public.depts sortby public.depts.deptno project public.depts.name`
Is this something you can easily fix?

Here is an overview on the most important changes I did:
- Separated CQL interface from REST interface and added a simple HTTP interface for submitting CQL queries using port 8087.
- Use POST requests instead of GET requests (GET with body is not supported by all clients). 
- Reorganized the tests and moved some tests into the cql-interface module.

The README file we would like to put on the website, if this is ok for you?

**Comment by VishalDalwadi** [comment]
Hi @vogti. Yes, all of those changes are fine by me. I will sort out the issue. I believe we are creating the sort node after creating the projection node, so a reference to the sorting node cannot be created. But I am not completely sure. I will look into it. No worries.

**Comment by VishalDalwadi** [comment]
I've restored the README file and documented the behavior for sorting on a column that is not present in projection.

**Review by vogti — APPROVED** [review]
Thanks, @VishalDalwadi, for this PR!

**Comment by VishalDalwadi** [comment]
> Thanks, @VishalDalwadi, for this PR!

Thanks, @vogti, @hennlo, @cedricmendelin for your help along the way. I look forward to working with you again.

**Pull request merged**
