### PR TITLE
Add '-version' as command line option

### LINKED ISSUE #424: Add ` -version` as additional command line option
### Affected Areas

DB

### Feature Description

Add ` -v | --version` as additional command line option to retrieve the installed version of Polypheny.

Currently the `polypheny` command line hook does only support runtime flags such as:
```bash
NAME
        polypheny-db - Polypheny-DB command line hook.

SYNOPSIS
        polypheny-db [ -daemon ] [ -defaultSource <defaultSourceName> ]
                [ -defaultStore <defaultStoreName> ] [ -gui ] [ {-h | --help} ]
                [ -memoryCatalog ] [ -resetCatalog ] [ -resetDocker ]
                [ -testMode ]

OPTIONS
        -daemon
            Disable splash screen

        -defaultSource <defaultSourceName>
            Type of default source

        -defaultStore <defaultStoreName>
            Type of default store

        -gui
            Show splash screen on startup and add taskbar gui

        -h, --help
            Display help information

        -memoryCatalog
            Store catalog only in-memory

        -resetCatalog
            Reset the catalog

        -resetDocker
            Removes all Docker instances, which are from previous Polypheny
            runs.

        -testMode
            Special catalog configuration for running tests
```

### Use Case(s)

Easy to use functionality to obtain installed version of Polypheny

### Possible Solutions

Add option in PolyphenyDb.java alongside the existing options.

### Possible Alternatives

_No response_

### PR DESCRIPTION
**Pull request by rit-clone**
## Summary

Fixed #424 

### Changes

Added additional command line option `-v` & `--version` to retrieve currently installed version of Polypheny-DB

---

### ToDo

- [x] Verify design and implementation

### CODE REVIEW

**Comment by rit-clone** [comment]
@hennlo Can you please review this PR?

**Comment by hennlo** [comment]
@rit-clone Thanks for submitting the PR.
I've a few remarks that you could work on.

1.) Your original idea with the `log.info`is much cleaner to work with, therefore please refrain from using System.out
2.) You could also add a short option for querying the version, similiar to the help option you can do: `-v | --version`
3.) I'm afraid `polyphenyDb.getClass().getPackage().getImplementationVersion()` won't return Polypheny-DB's version but null.
You'll need to retrieve the version as specified in `gradle.properties` file. However you cannot read the file from file system and need to access the version internally.

**Comment by rit-clone** [comment]
@hennlo I'll make the changes for `log.info` and adding `-v` option as well. For point no.3, since Implementation version is referred from `gradle.properties` to `build.gradle` (https://github.com/polypheny/Polypheny-DB/blob/master/build.gradle#L25) and that version is in turn referred to dbms package's `build.gradle` (https://github.com/polypheny/Polypheny-DB/blob/master/dbms/build.gradle#L248) , the implementation version gets set while building. It will be null if you run it in an IDE but if the jar is run, I see the version. 
Screenshot 2022-12-06 at 4 04 49 PM

**Comment by hennlo** [comment]
@rit-clone Good catch, you're absolutely right, my bad. 👍
Also I thought about the Log output and the longer I think about it I like your solution actually better.

So to summarize:
Only 1.) is open for this PR

**Comment by rit-clone** [comment]
Made the required changes. @hennlo please review.

**Review by hennlo — APPROVED** [review]
PR looks good.

**Comment by hennlo** [comment]
Thx @rit-clone, for this PR!

**Pull request merged**
