### PR TITLE
Excel data source adapter

### PR DESCRIPTION
**Pull request by zxie86**
## Final Report: GSoC '22

- Student Name: Zhiqi Xie (Kelly)
- Organization: [Polypheny](https://polypheny.org/)
- Mentors: [Isabel](https://github.com/isabelge), [Marc](https://github.com/hennlo)
- Project: [Data Source Adapter for Excel Sheets](https://summerofcode.withgoogle.com/programs/2022/projects/axdeCi5w)

### Projects

This PR has been created as part of the Google Summer of Code in the "Data Source Adapter for Excel Sheets" project.
I have created an adapter to query the Excel Sheets. This adapter allows Polypheny to interact with Excel sheets and query the mapped data.

This adapter is able to handle both XLS (Excel ’97) and XLSX (Excel 2007) formats of spreadsheets. It uses the [Apache POI](https://poi.apache.org/) to extract data from Excel sheets.

---

### Features

* Able to perform the following basic operations:

1. TableScan
2. Project
3. Filter
4. Aggregate
5. Sort

* Able to recognize the following date formats:

1. yyyy-mm-dd
2. dd.mm.yyyy

* Able to import Excel formats:

1. XLS
2. XLSX

---

### Constraints and Future Improvement

The adapter is able to add one sheet at a time. It would be great to have an "add all sheets from an Excel file" function.

---
### Thank you
Thank you Polypheny and Google Summer of Code for this amazing opportunity. I learned and applied my coding skills during this event. Special thanks to my mentors Isabel Geissmann and Marc Hennemann for helping me when I ran into issues, and Marc Vogt for helping with my proposal.

### CODE REVIEW

**Comment by hennlo** [comment]
@zxie86 Thanks for the PR and your contribution.
We're just going through your PR and have a few remarks or adjustments that you should take a look at

**1. Source can be created without a source file**
image
Although you make sure that the name is specified and unique you still omit checking if a source file is selected or if it even exists.
This results in creating sources that have no content attached.
* Check if the directory field has an input
* Check that the input within directory even exists.

**2. The unique sourceName is not used within the catalog or the schema view. rather the filename of the xlsx file.**
image
image
This is difficult to digest if your source file has multiple sheets. and you want to add all of them they will look somethin like this
public.excel_adapter_test_data
public.excel_adapter_test_data0
public.excel_adapter_test_data1
* Make sure that you don't use the filename as the table object name but maybe insert another textfield for the adapter, stating what the **objectName** should be.

**Review by datomo — APPROVED** [review]
Most suggestions from Marc are sadly handled similarly for all Sources and will be adjusted for all of them in a single solution. This PR is for me good to go.

**Review by vogti — APPROVED** [review]
Thx, @zxie86, for this PR!

**Review by NigamAnanya — COMMENTED** [review]
PR's are good to go

**Pull request merged**
