### PR TITLE
Data Statistics for Temporal Columns

### LINKED ISSUE #191: Support for temporal types in graphical query builder
The graphical query builder only supports building conditions for numerical and character types. Adding support for temporal types requires extending to the statistics manager in Polypheny-DB (`org/polypheny/db/statistic/StatisticsManager.java`) and the corresponding component in the Polypheny-UI.

### PR DESCRIPTION
**Pull request by earthshakira**
- created TemporalStatisticColumn
 - Added related changes to StatisticsManager

closes #191

### CODE REVIEW

**Review by datomo — COMMENTED** [review]
Hey earthshakira
Thank you very much for your PR. Please check my suggestions.
Else this looks really good and elevates the dynamic querying quite a bit. 

After the null-unique bug is fixed this PR is good from my point of view.

**Comment by earthshakira** [comment]
@datomo Have made the required changes, please review once

**Comment by datomo** [comment]
Thank you very much for your changes @earthshakira , this looks good to me.

**Review by datomo — APPROVED** [review]
Thank you very much for your changes @earthshakira , this looks good to me.

**Pull request merged**
