### PR TITLE
Prism Query Interface: Replace gRPC with custom handling of messages

### PR DESCRIPTION
**Pull request by gartens**
This removes gRPC in favor of sending/receiving the protobuf encoded messages ourselves.  This gives us better control to rollback transactions immediately when the connection is closed, allows us to support different transport methods (TCP and UNIX) and depending on the transport to authenticate clients directly (UNIX).

Various messages and serializations are improved as well.

## Additional Changes
- Ways to distinguish between auto generated and manual queries
- Constratint enforcement, moved the physical execution to the commit, to prevent physical rollback challenges

## Fixes
- Restore of IdBuilder
- Large number on various stores
- Correct Result number in Neo4j for prepared queries
- Added missing commits for some Neo4j DD queries

## ToDo

- [x] Delete socket files when stopping polypheny?
- [x] Fix neo4J test

### CODE REVIEW

**Review by datomo — APPROVED** [review]
Thx @gartens for this PR.

**Comment by datomo** [comment]
@gartens is this ready for review and merge, or do you have anything to add?

**Comment by gartens** [comment]
Go ahead @datomo.

**Review by vogti — APPROVED** [review]
Thx, @gartens, @TobiasHafner, and @datomo, for this PR!

**Pull request merged**
